### ISSUE TITLE
mainflux-cli: command not found

### ISSUE THREAD

**Issue by wassim6975** [mainflux/cli#1]
Hello everyone, 

I have a problem when I want to try to use mainflux-cli . 

So first after git clone in /Users/wassim/go/src/github;com/mainflux/mainflux  
I did make cli 
MacBook-Air-de-wassim:mainflux wassimb$ make cli
CGO_ENABLED=0 GOOS= GOARCH=amd64 GOARM= go build -ldflags "-s -w" -o 
build/mainflux-cli cmd/cli/main.go

And there was no problem 

And after I wanted to try the mainflux-cli tool, so I did 
MacBook-Air-de-wassim:mainflux wassim$ mainflux-cli version
-bash: mainflux-cli: command not found

My mainflux-cli is in Users/wassim/go/src/github;com/mainflux
And my mainflux in Users/wassim/go/src/github;com/mainflux/mainflux 

Can you help me ? 

Thank you in advance for your help :)

**Comment by drasko** [comment]
@wassim6975 Mainflux team is overloaded and has no time to help you with trivial Go programming issues.

Mainflux is a complex Go project and is not a best place to start if you are learning Go programming.

Please do not open issues for such a questions, try reaching for help over the [Gitter channel](https://gitter.im/Mainflux/mainflux).

Use `go get` to get your Mainflux packages if you do not master `$GOPATH` and `git clone`, and also open and read `Makefile` and try to understand what it is doing. Compiled binaries are put into `build` dir for now.

**Comment by drasko** [comment]
Also, use Monorepo CLI: https://github.com/mainflux/mainflux/tree/master/cli

This repo is just a placeholder that is not functional for now - we are in transition of separating the monorepo in several repos.

**Comment by wassim6975** [comment]
Ok thank you very much, I'll check and sorry for bothering you.
